image: python:3.12

stages:
  - scrape

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key:
    files:
      - requirements.txt
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install --disable-pip-version-check -r requirements.txt
  - playwright install chromium

scrape_jobs:
  stage: scrape
  script:
    - python scraper.py
  only:
    - schedules